# Site settings
title: EinBlick Vienna
header-img: img/home-bg.jpg
email: ksenia.disterhof@web.de
description: "EinBlick hinter die Fassaden. Innenhöfe – Ein verborgenes Wien"
baseurl: "https://kseniadisterhof.github.io"
url: "https://kseniadisterhof.github.io/einblick-vienna"
email_username:  ksenia.disterhof@web.de
permalink: /:title/

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

years:
- 2017
- 2016
- 2015
- 2014


mapbox-token: pk.eyJ1IjoiYXJ0aHVyc29hcmVzIiwiYSI6ImNqMmVtMHNodTA3dDUycXBpdnYwODVjcDkifQ.jXP-sC6Lu307Fg5jhtlP1w
mapid: mapbox.dark
mapid-winter: mapbox.dark
mapboxjs: v3.0.1
leafletjs: v1.0.0
jquery: 3.1.1
modernizr: 2.8.3

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
